Add model entity
Java-Arctic-Ratel/repair-service pull request #1
Opened 2019-10-24 10:50 UTC by sergeyarhutik

add model

2019-10-24 11:07 UTC, aleksieiev requested changes

2019-10-24 11:07 UTC, aleksieiev commented on repair-service/model/src/main/java/com/epam/Address.java
> +    public Address(String houseNumber, String apartmentNumber, Integer clientAddressId, Integer cityId, Integer streetId) {
Do you really need this constructor?

2019-10-24 11:07 UTC, aleksieiev commented on repair-service/model/src/main/java/com/epam/Client.java
> + * The type Client.
`Class represents entity with client information of repairing service.`
JavaDoc should be informative. I see that this is a `class Client`

2019-10-24 11:07 UTC, aleksieiev commented on repair-service/model/src/main/java/com/epam/Street.java
> +
redundant empty line

2019-10-24 11:07 UTC, aleksieiev commented on repair-service/model/src/main/java/com/epam/Client.java
> +
redundant empty lines between private fields

2019-10-24 11:07 UTC, aleksieiev commented on repair-service/model/src/main/java/com/epam/City.java
> +
2 empty lines. what for?

2019-10-24 12:15 UTC, sergeyarhutik commented on repair-service/model/src/main/java/com/epam/Address.java
> +    public Address(String houseNumber, String apartmentNumber, Integer clientAddressId, Integer cityId, Integer streetId) {
I use constructors everywhere. should I remove them? then if we need them I can add them later

2019-10-24 12:29 UTC, aleksieiev commented on repair-service/model/src/main/java/com/epam/Address.java
> +    public Address(String houseNumber, String apartmentNumber, Integer clientAddressId, Integer cityId, Integer streetId) {
1. think it's redundant right now
2. It also possible to have setters which returns the same object and it will be like `Builder` pattern

2019-10-24 13:15 UTC, RomanukAlex approved these changes

2019-10-25 10:45 UTC, aleksieiev approved these changes

2019-10-25 10:46 UTC, aleksieiev commented
Please merge it when you're ready

2019-10-25 11:04 UTC, RomanukAlex approved these changes

2019-10-25 11:08 UTC, sergeyarhutik commented
Merging is blocked

2019-10-25 11:12 UTC, aleksieiev commented
![image](https://user-images.githubusercontent.com/21191367/67566845-6915b800-f731-11e9-9778-7fe742451169.png)

2019-10-25 11:18 UTC, sergeyarhutik commented
![123](https://user-images.githubusercontent.com/51294905/67567266-446e1000-f732-11e9-8d86-5c8d8ecaddad.jpg)

2019-10-25 11:29 UTC, aleksieiev commented
now?

2019-10-25 11:31 UTC, merged