Create .travis.yml
Java-Arctic-Ratel/repair-service pull request #6
Opened 2019-10-24 14:10 UTC by sergeyarhutik

2019-10-24 14:15 UTC, aleksieiev requested changes

2019-10-24 14:15 UTC, aleksieiev commented on .travis.yml
> +script: "mvn cobertura:cobertura"
as far as I remember we discussed to use Gradle as build tool.
Think mvn isn't suitable in this case

2019-10-24 14:15 UTC, aleksieiev commented on .travis.yml
> +language: java
check please is it required to specify Java version?
We agreed to use J11, think it can be configured also because it's very important for build.

2019-10-29 10:27 UTC, aleksieiev approved these changes

2019-10-29 10:27 UTC, aleksieiev commented on .travis.yml
> +  - cd repair-service/
why do we need to open specific dir here?
Maybe it would be better to change project structure as well as build tool?

2019-10-29 10:27 UTC, aleksieiev commented on .travis.yml
> +  - chmod +x gradlew
the same here. Think we can commit this changes once and forget about this.

2019-10-29 12:40 UTC, RomanukAlex approved these changes

2019-10-30 11:20 UTC, merged